name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run Tests
        shell: powershell
        run: |
          $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
          if (-not $isAdmin) {
            Write-Error "Not running as Administrator"
            exit 1
          }

          gotestsum --format pkgname `
            --junitfile test-results.xml `
            --jsonfile test-output.json `
            -- -v ./...

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results.xml
            test-output.json
